#
# ~/.zlogin
#

function compile-ssh-config {
	cat <<-'EOF' > $HOME/.ssh/config
	# WARNING: This file is generated by ~/.zlogin; local changes will be overwritten!
	EOF
	for file in $HOME/.ssh/config.d/*; do
		printf '\n##### %s\n\n' "$file" >> $HOME/.ssh/config
		cat "$file" >> $HOME/.ssh/config
	done
}

if (( $+commands[ssh] )) && [[ -d $HOME/.ssh/config.d ]]; then
	compile-ssh-config
fi
