format = """
$username\
$hostname\
$shlvl\
$kubernetes\
$directory\
$git_branch\
$git_commit\
$git_state\
$git_status\
$nix_shell\
$cmd_duration\
$line_break\
$jobs\
$battery\
$status\
$character"""

[directory]
truncation_length = 4
truncation_symbol = "…/"

[character]
success_symbol = "[▶](bold green)"
error_symbol = "[●](bold red)"
