set --global fish_color_autosuggestion 7c7e85
set --global fish_color_cancel --reverse
set --global fish_color_command brcyan
set --global fish_color_comment a0a1a7 --italics
set --global fish_color_cwd green
set --global fish_color_cwd_root red
set --global fish_color_end a0a1a7
set --global fish_color_error red
set --global fish_color_escape red
set --global fish_color_history_current --bold
set --global fish_color_host brcyan
set --global fish_color_host_remote brred
set --global fish_color_keyword magenta
set --global fish_color_normal normal
set --global fish_color_operator brgreen
set --global fish_color_option red
set --global fish_color_param normal
set --global fish_color_quote green
set --global fish_color_redirection brred
set --global fish_color_search_match --background cyan
set --global fish_color_selection 595e64 --background bryellow
set --global fish_color_user brgreen
set --global fish_color_valid_path cyan --underline
set --global fish_pager_color_background
set --global fish_pager_color_completion 7c7e85
set --global fish_pager_color_description a0a1a7 --italics
set --global fish_pager_color_prefix 393f46 --bold --underline
set --global fish_pager_color_progress brwhite --background cyan
set --global fish_pager_color_secondary_background
set --global fish_pager_color_secondary_completion
set --global fish_pager_color_secondary_description
set --global fish_pager_color_secondary_prefix
set --global fish_pager_color_selected_background --background brcyan
set --global fish_pager_color_selected_completion e0e1e1
set --global fish_pager_color_selected_description c6c7c7 --italics
set --global fish_pager_color_selected_prefix brwhite --bold --underline
