[aliases]
l = ["log", "-r", "all() ~ EMPTY_MERGES"]
ll = [
  "log",
  "-r",
  "all() ~ EMPTY_MERGES",
  "-T",
  "builtin_log_compact_full_description"
]
release-log = [
  "log",
  "-r",
  "latest(tags()):: & ~@",
  "-T",
  "builtin_log_compact_full_description"
]

[revset-aliases]
EMPTY_MERGES = "merges() & empty()"
MINE = 'author(exact:"aaron@elasticdog.com")'
MY_HEADS = "((visible_heads() & MINE) | @)"
DEFAULT = "MY_HEADS | trunk() | (::MY_HEADS~::trunk()) | (::MY_HEADS~::trunk())-"

[revsets]
log = "DEFAULT"

[signing]
behavior = "own"
backend = "ssh"
key = "~/.ssh/id_ed25519_sign.pub"

[snapshot]
max-new-file-size = "2MiB"

[templates]
draft_commit_description = '''
concat(
  builtin_draft_commit_description,
  "\nJJ: ignore-rest\n",
  diff.git(),
)
'''
log = "builtin_log_comfortable"

[template-aliases]
show = "builtin_log_detailed"

[user]
name = "Aaron Bull Schaefer"
email = "aaron@elasticdog.com"

[ui]
default-command = "log"
