theme = "catppuccin_macchiato_transparent"

[editor]
color-modes = true
cursorline = true
end-of-line-diagnostics = "hint"
true-color = true  # required for blink shell

[editor.statusline]
right = [
  "diagnostics",
  "selections",
  "separator",
  "position",
  "position-percentage",
  "spacer",
  "separator",
  "file-encoding",
  "file-type",
]
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"

[editor.file-picker]
hidden = false

[editor.indent-guides]
render = true
skip-levels = 1

[editor.inline-diagnostics]
cursor-line = "hint"

[editor.lsp]
display-inlay-hints = true

[keys.normal]
A-q = "@<C-s>mip:reflow<ret><C-o>,<A-;>l"

[keys.insert]
A-q = "@<esc><C-s>mip:reflow<ret><C-o>li"
