[[language]]
name = "bash"
indent = { tab-width = 4, unit = "\t" }
formatter = { command = "shfmt", args = ["--simplify"] }
auto-format = true

[[language]]
name = "css"
formatter = { command = "prettier", args = ["--parser", "css"] }
auto-format = true

[[language]]
name = "cue"
formatter = { command = "cue", args = ["fmt", "--simplify", "-"] }

[[language]]
name = "fish"
formatter = { command = "fish_indent" }
auto-format = true

[[language]]
name = "jj-description"
scope = "source.jjdescription"
comment-token = "JJ:"
file-types = ["jjdescription"]
roots = []
indent = { tab-width = 2, unit = "  " }
rulers = [51, 73]
text-width = 72

[[language]]
name = "json"
formatter = { command = "prettier", args = ["--parser", "json"] }

[[language]]
name = "markdown"
formatter = { command = "prettier", args = [
  "--parser",
  "markdown",
  "--prose-wrap",
  "always",
] }

[[language]]
name = "toml"
formatter = { command = "taplo", args = ["format", "-"] }

[[language]]
name = "yaml"
formatter = { command = "prettier", args = ["--parser", "yaml"] }
auto-format = true

### LANGUAGE SERVERS

[[language-server.rust-analyzer.config]]
check.command = "clippy"
check.extraArgs = ["--locked"]
rustfmt.extraArgs = ["+nightly"]
