[aliases]
l = ["log", "-r", "all() ~ EMPTY_MERGES"]
ll = ["log", "-r", "all() ~ EMPTY_MERGES", "-T", "builtin_log_detailed"]

[revsets]
log = "DEFAULT"

[revset-aliases]
EMPTY_MERGES = 'merges() & empty()'
MINE = 'author("aaron@elasticdog.com")'
MY_HEADS = "((visible_heads() & MINE) | @)"
DEFAULT = "MY_HEADS | trunk() | (::MY_HEADS~::trunk()) | (::MY_HEADS~::trunk())-"

[templates]
log = "builtin_log_comfortable"

[template-aliases]
show = "builtin_log_detailed"

[user]
name = "Aaron Bull Schaefer"
email = "aaron@elasticdog.com"

[ui]
default-command = "log"

[snapshot]
max-new-file-size = "2MiB"
