#!/usr/bin/env bash

current_branch=$(git symbolic-ref -q HEAD | sed -e 's|^refs/heads/||')

if [[ $current_branch = 'master' ]]; then
	printf 'Direct commits to the master branch are not allowed.\n'
	exit 1
fi
